### ISSUE TITLE
install with conda --but it have bug

### ISSUE THREAD

**Issue by hamidmosaddeghi** [cgkmw-durham/cg_param_m3#2]
Hi I install it with your installation method;

(cg_param) server@info:~/cg_param_m3-main$ ./cg_param_m3.py "CC1=C2C(C(=O)C3(C(CC4C(C3C(C(C2(C)C)(CC1OC(=O)C(C(C5=CC=CC=C5)NC(=O)OC(C)(C)C)O)O)OC(=O)C6=CC=CC=C6)(CO4)OC(=O)C)O)C)O" new.gro new.itp 0
./cg_param_m3.py:110: RuntimeWarning: divide by zero encountered in true_divide
  scores = scores/np.amin(scores)
./cg_param_m3.py:110: RuntimeWarning: invalid value encountered in true_divide
  scores = scores/np.amin(scores)
Traceback (most recent call last):
  File "./cg_param_m3.py", line 1310, in <module>
    A_cg,beads,ring_beads,path_matrix = mapping(mol,ring_atoms,matched_maps,3)
  File "./cg_param_m3.py", line 572, in mapping
    ring_beads,comp,A_init = group_rings(A_atom,ring_atoms,matched_maps,mol)
  File "./cg_param_m3.py", line 456, in group_rings
    new_groups.append([indices[x] for x in bead])
  File "./cg_param_m3.py", line 456, in <listcomp>
    new_groups.append([indices[x] for x in bead])
IndexError: list index out of range

how solve it?

**Comment by wulfbear** [comment]
Hi, 
I have encountered the same issue with the latest version installed according to the readme.md.
Command line:
`python cg_param_m3.py "[C@H](O)(C)C(=O)O[C@H](C(=O)O[C@H](C(=O)O[C@H](C(=O)OCC)C)C)C.O(C)O.O(C(=O)CC)[C@H](C(=O)O[C@H](C(=O)O[C@H](C(=O)OCC)C)C)C.O(C)O.O(C(=O)CC)[C@H](C(=O)O[C@H](C(=O)O[C@H](C(=O)OCC)C)C)C.O(C)O.O(C(=O)CC)[C@H](C(=O)O[C@H](C(=O)O[C@H](C(=O)O[C@H](C=O)C)C)C)C.O" mol.gro top.itp 0`

Error message:
```
RuntimeWarning: divide by zero encountered in divide
  scores = scores/np.amin(scores)
/mnt/f/01_PhDBioinformatics/05_MARTINI/03_Polymer/PLA/PLA/cg_param_m3.py:105: RuntimeWarning: invalid value encountered in divide
  scores = scores/np.amin(scores)
Traceback (most recent call last):
  File "cg_param_m3.py", line 1309, in <module>
    A_cg,beads,ring_beads,path_matrix = mapping(mol,ring_atoms,matched_maps,3)
  File "cg_param_m3.py", line 570, in mapping
    results_dict_final = postprocessing(results,ring_atoms,n_iter,A_init,w_init,path_matrix,matched_maps)
  File "cg_param_m3.py", line 478, in postprocessing
    results_dict,ring_atoms,exclusion_list= path_contraction(last_iter,postprocess,A_init,w_init,ring_atoms,matched_maps,path_matrix,exclusion_list)
  File "cg_param_m3.py", line 497, in path_contraction
    groups,ring_beads,exclusion_list = lone_atom(ties,oldA,A_init,scores,ring_beads,matched_maps,comp,exclusion_list)
  File "cg_param_m3.py", line 153, in lone_atom
    score_prev = scores[bonded[bonded_sorted[0]]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

@hamidmosaddeghi Have you been able to solve this issue?

Best regards!

**Comment by EKearn** [comment]
Hi there,

Apologies for the slow response! Firstly for @hamidmosaddeghi. The bug fix uploaded to the github in May 2023 seem to have fixed this issue. When I run the current version on the github, I get the divide by zero error but not the index out of bounds error. The divide by zero is a separate bug to do with the ring grouping subroutine trying to compare ring atoms which are not adjacent. While undesirable (suboptimal), it still produces a working model. Are you using the most up to date version of the script?

Secondly, @hamidmosaddeghi. I have been able to replicate the error for your molecule. Now the divide by zero error is causing fatal issues. It appears to be due to your unusual smiles code. This results in 4 separate fragments, crashing the script. Can you rewrite the script without the use of '.'? I cannot quite identify what molecule you're going for.

I'll be more on top of the Github from now on. Thanks for using cg_param!
