### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by yajairazepeda** [cgkmw-durham/cg_param_m3#5]
I have a issue with this SMILES "CCCCCCCCCCCCOC4CCC(C(=O)OCC(COC(=O)C1CC(OCCCCCCCCCCCC)CC(OCCCCCCCCCCCC)C1)(COC(=O)C2CC(OCCOCCOCCOC)C(OCCOCCOCCOC)C(OCCOCCOCCOC)C2)NC(=O)C3CC(OCCOCCOCCOC)C(OCCOCCOCCOC)C(OCCOCCOCCOC)C3)C(OCCCCCCCCCCCC)C4.CC". This is my error: 
```
RuntimeWarning: divide by zero encountered in divide
  scores = scores/np.amin(scores)
/home/b/Yajaira/gromacuda/cg_param_m3-martini3_v2/cg_param_m3.py:105: RuntimeWarning: invalid value encountered in divide
  scores = scores/np.amin(scores)
Traceback (most recent call last):
  File "/home/b/Yajaira/gromacuda/cg_param_m3-martini3_v2/cg_param_m3.py", line 1313, in <module>
    A_cg,beads,ring_beads,path_matrix = mapping(mol,ring_atoms,matched_maps,3)
  File "/home/b/Yajaira/gromacuda/cg_param_m3-martini3_v2/cg_param_m3.py", line 570, in mapping
    results_dict_final = postprocessing(results,ring_atoms,n_iter,A_init,w_init,path_matrix,matched_maps)
  File "/home/b/Yajaira/gromacuda/cg_param_m3-martini3_v2/cg_param_m3.py", line 478, in postprocessing
    results_dict,ring_atoms,exclusion_list= path_contraction(last_iter,postprocess,A_init,w_init,ring_atoms,matched_maps,path_matrix,exclusion_list)
  File "/home/b/Yajaira/gromacuda/cg_param_m3-martini3_v2/cg_param_m3.py", line 497, in path_contraction
    groups,ring_beads,exclusion_list = lone_atom(ties,oldA,A_init,scores,ring_beads,matched_maps,comp,exclusion_list)
  File "/home/b/Yajaira/gromacuda/cg_param_m3-martini3_v2/cg_param_m3.py", line 153, in lone_atom
    score_prev = scores[bonded[bonded_sorted[0]]]
IndexError: index 0 is out of bounds for axis 0 with size 0


```
Do you know how can I solve it? 
Thank you so much.

**Comment by yajairazepeda** [comment]
.

**Comment by EKearn** [comment]
Hi there,

Apologies for the slow respone. Why is there a '.' before the last two carbons in the SMILE? This indicates that the last two atoms are not bonded to the rest of the molecules, which cg_param can't handle. Remove it and the code should work, though you'll need to work out where you want the two carbons to go.

Many thanks,
Eoin

**Comment by yuhaihaiyu** [comment]
Dear developer
I encountered the same error when I wanted to produce the itp file of hydrazine monohydrate. Because its SMILE NN.O from the PubChem website also encloses a ".".   So how can I obtain a correct the itp file of hydrazine monohydrate.

**Comment by EKearn** [comment]
Hi there,

Again you'll have to remove the ".O". The script ignores hydration data, so it can produce a model hydrazine in solution, NN, but not the monohydrate solid form. You need a continuous SMILES. For monohydrate I'm not sure how you'd proceed, but taking the base NN model would be a good starting point

Many thanks,
Eoin

**Comment by yuhaihaiyu** [comment]
I agree with you, so is it true that I built a model with the following itp file to simulate the evaporation of hydrazine hydrate solution.&nbsp;
[ moleculetype ]
; molname &nbsp; nrexcl
N2H4_H2O &nbsp; &nbsp;1


[ atoms ]
; nr &nbsp; type &nbsp; resnr &nbsp;residue &nbsp;atom &nbsp;cgnr &nbsp;charge
1 &nbsp; &nbsp; TNxd &nbsp; &nbsp;1 &nbsp; &nbsp; &nbsp;HHYD &nbsp; &nbsp; N2H4 &nbsp; 1 &nbsp; &nbsp; 0.0
2 &nbsp; &nbsp; TW-a &nbsp; &nbsp;1 &nbsp; &nbsp; &nbsp;HHYD &nbsp; &nbsp; H2O &nbsp; &nbsp;2 &nbsp; &nbsp; 0.0


[ bonds ]
; &nbsp;ai &nbsp; aj &nbsp; funct &nbsp; length &nbsp; k
1 &nbsp; 2 &nbsp; &nbsp;1 &nbsp; &nbsp;0.47 &nbsp; &nbsp;5000 &nbsp; ; flexible bond ~0.47 nm
