### ISSUE TITLE
SyntaxWarning

### ISSUE THREAD

**Issue by 550cw** [cgkmw-durham/cg_param_m3#6]
I have a issue with python cg_param_m3.py "CC[C@@H]1[C@H](C2=CC3=C(C(=C4[N-]3[Mg+2]56[N]2=C1C=C7[N-]5C8=C([C@H](C(=O)C8=C7C)C(=O)OC)C9=[N]6C(=C4)[C@H]([C@@H]9CCC(=O)OC/C=C(\C)/CCC[C@H](C)CCC[C@H](C)CCCC(C)C)C)C)C(=O)C)C" BCL_CG.gro BCL_CG.itp BCL y. This is my error:

/home/zhangyq/cg_param/cg_param_m3.py:637: SyntaxWarning: invalid escape sequence '\]'
  lc = re.compile('[cn([nH\])os]+')
Traceback (most recent call last):
  File "/home/zhangyq/cg_param/cg_param_m3.py", line 1317, in <module>
    tuning = bool(int(sys.argv[4]))
                  ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'BCL'
(cg_param) [zhangyq@arg cg_param]$ python cg_param_m3.py "CC[C@@H]1[C@H](C2=CC3=C(C(=C4[N-]3[Mg+2]56[N]2=C1C=C7[N-]5C8=C([C@H](C(=O)C8=C7C)C(=O)OC)C9=[N]6C(=C4)[C@H]([C@@H]9CCC(=O)OC/C=C(\C)/CCC[C@H](C)CCC[C@H](C)CCCC(C)C)C)C)C(=O)C)C" BCL_CG.gro BCL_CG.itp BCL n
/home/zhangyq/cg_param/cg_param_m3.py:637: SyntaxWarning: invalid escape sequence '\]'
  lc = re.compile('[cn([nH\])os]+')
Traceback (most recent call last):
  File "/home/zhangyq/cg_param/cg_param_m3.py", line 1317, in <module>
    tuning = bool(int(sys.argv[4]))
                  ^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'BCL'

Do you know how can I solve it?
Thank you so much.

**Comment by 550cw** [comment]
(cg_param) [zhangyq@arg cg_param]$ python cg_param_m3.py "CC[C@@H]1[C@H](C2=CC3=C(C(=C4[N-]3[Mg+2]56[N]2=C1C=C7[N-]5C8=C([C@H](C(=O)C8=C7C)C(=O)OC)C9=[N]6C(=C4)[C@H]([C@@H]9CCC(=O)OC/C=C(\\C)/CCC[C@H](C)CCC[C@H](C)CCCC(C)C)C)C)C(=O)C)C" BCL_CG.gro BCL_CG.itp 0
/home/zhangyq/cg_param/cg_param_m3.py:637: SyntaxWarning: invalid escape sequence '\]'
  lc = re.compile('[cn([nH\])os]+')
False
[N-]->[Mg+2](<-[N-])(<-N)<-N not on list
[N-]->[Mg+2](<-[N-])(<-N)<-N Data from Wildmann-Crippen
[20:38:47] UFFTYPER: Unrecognized charge state for atom: 11
new issu

**Comment by EKearn** [comment]
Hi there,

I don't recognise your SMILES, could you simplify it or tell me what molecule it is? Is it pentane?  I cannot currently reproduce your UFFTYPER error.

The error above is due to a redundant line, 637, that you can comment out. It wasn't causing problems until a recent python update, but I will remove it in the main branch shortly.

Thanks for messaging,
Eoin
